steps:
- script: npm install && npm test
  displayName: Run tests
  continueOnError: true

- script: |
    set
    PACKAGE_VERSION=$(node -p "require('./package.json').version")

    if [ -n "$SYSTEM_PULLREQUEST_PULLREQUESTNUMBER" ]; then
      VERSION_STRING=${PACKAGE_VERSION}-pr-${SYSTEM_PULLREQUEST_PULLREQUESTNUMBER}-$(git rev-parse --short HEAD)
    else
      VERSION_STRING=${PACKAGE_VERSION}-ci-$(git rev-parse --short HEAD)
    fi

    npm --no-git-tag-version version $VERSION_STRING
    echo "##vso[build.updatebuildnumber]${VERSION_STRING}_${BUILD_BUILDID}"
  displayName: Indicate CI or PR version

- script: |
    mkdir ~/.npm-global
    export NPM_CONFIG_PREFIX=~/.npm-global
    export PATH=~/.npm-global/bin:$PATH
    npm install -g vsce
    vsce package
  displayName: Create VSIX

- task: CopyFiles@2
  displayName: Stage VSIX for publishing
  inputs:
    contents: '*.vsix' 
    targetFolder: $(Build.ArtifactStagingDirectory)

- task: PublishBuildArtifacts@1
  displayName: Publish VSIX
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)
    artifactName: VSIX