trigger:
  batch: true
  branches:
    include:
    - main
    - releases/*
    exclude:
    - releases/old*
  paths:
    include:
    - '*'
    exclude:
    - readme.md
    - docs/*
steps:
- script: echo hello